export const API_BASE = "http://localhost:3001"
export const ContactNumber = "05347205019"
export const E_MAIL = "emrebaskayaaa@gmail.com"
export const Instagram = ""
export const Dribbble = ""
export const Twitter = ""
export const Youtube = ""
export const GOOGLE_CLIENT_ID ="421538292776-jgbu8j6rc3ltn84vug1fpuaakfjj4od3.apps.googleusercontent.com"